src/accounts/api/urls.py
from django.conf.urls import url
from .views import UsersSerializerListAPIView
from tweets.api.views import TweetSerializerListAPIView
app_name="api"

urlpatterns = [


    ##api serializer
    url(r'^users/$', UsersSerializerListAPIView.as_view(), name='all-users'),
    url(r'profile/(?P<slug>[\w.@+-]+)/$', TweetSerializerListAPIView.as_view(),name='users_tweets'),
]

src/accounts/password/urls.py
# accounts.passwords.urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


# app_name="Guest.password"


urlpatterns  = [

url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),






url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),





url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),






url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

src/accounts/urls.py
from django.conf.urls import include,url
from .views import Register,ProfileView,ToggleFollow,UpdateProfileView,GetAllUsers
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy,reverse
from .views import CustomLoginView
app_name = 'accounts'

urlpatterns = [


   url(r'related_users/$', GetAllUsers.as_view(),name='all'),
   url(r'profile/(?P<slug>[\w.@+-]+)/$', ProfileView.as_view(),name='profile'),
   url(r'profile/(?P<slug>[\w.@+-]+)/update$', UpdateProfileView.as_view(),name='update_profile'),
   url(r'profile/follow/(?P<slug>[\w.@+-]+)$', ToggleFollow.as_view(), name='Follow'),

   url('register/',Register.as_view(),name='register'),
   url('login/', CustomLoginView.as_view(),name='login'),




   url('logout/', auth_views.LogoutView.as_view(), name='logout'),

   url('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),

   url('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),


]

src/tweetme/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('admin/', admin.site.urls),



    url('^',include('tweets.urls', namespace='tweets')),




    url('^api/tweet/',include('tweets.api.urls', namespace='api-tweet')),

    url('^api/accounts/',include('accounts.api.urls', namespace='api-accounts')),

    url('^api/tags/',include('Hashtag.api.urls', namespace='api-tags')),


    url('^accounts/',include('accounts.urls', namespace='accounts')),


    url('^accounts/',include('accounts.password.urls')),
    url('^tags/', include('Hashtag.urls', namespace='#tags')),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tweets/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from .views import GetTweet,DetailTweet,CreateTweet,SearchTweet,DeleteTweet,UpdateTweet,Retweet


app_name="tweets"

urlpatterns = [

    url(r'^$',GetTweet.as_view(),name='all'),
    url(r'^tweet/(?P<pk>\d+)/$',DetailTweet.as_view(),name='detail'),
    url(r'^tweet/create/$',CreateTweet.as_view(),name='create'),
    url(r'^tweet/delete/(?P<pk>\d+)/$',DeleteTweet.as_view(),name='delete'),
    url(r'^tweet/update/(?P<pk>\d+)/$',UpdateTweet.as_view(),name='update'),
    url(r'^tweet/search/$',SearchTweet.as_view(),name='search'),

    url(r'^tweet/(?P<pk>\d+)/retweet$', Retweet.as_view(), name='retweet'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import  get_user_model
from crispy_forms.helper import FormHelper,Layout
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import authenticate,login
from bootstrap_datepicker_plus import DatePickerInput
from django.utils.timezone import timezone
from datetime import datetime
from django.core import validators

User =get_user_model()

class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder':'Create password'}))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'placeholder':'Repeat password'}))

    class Meta:
        model = User
        fields = ('email', 'username')

        widgets = {
            'email':forms.EmailInput(attrs={'placeholder':'Email address'}),
            'username':forms.TextInput(attrs={'placeholder':'Username'}),  #  i removed 'class':'form-control' as the crispy automatically add it
            # 'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            # 'last_name': forms.TextInput(attrs={'placeholder': 'Surname'}),
        }


    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

def get_date():
    return timezone.localtime(timezone.now()).date()

DOY = ('1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015')

MONTHS = {	'01':'Janauary',
		'02':'February',
		'03':'March',
		'04':'April',
		'05':'May',
		'06':'June',
		'07':'July',
		'08':'August',
		'09':'September',
		'10':'October',
		'11':'November',
		'12':'December'		}

class ProfileForm(forms.ModelForm):
    image = forms.ImageField(required=False,help_text='The image should be cool.',label='profile picture')
    date_of_birth = forms.DateField(required=False,
                widget=forms.SelectDateWidget(years=DOY, empty_label=("Choose Year", "Choose Month", "Choose Day"))
            )

    class Meta:
        model = User
        exclude = [
            'is_active',
            'is_admin',
            'password',
            'last_login'
        ]
        widgets= {
            'first_name':forms.TextInput(attrs={'placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder':'Last Name'}),
        }


    # def save(self, commit=True):
    #     user=super().save(commit=False)
    #
    #     return user



    # def __init__(self,*args,**kwargs):
    #     # self.request= kwargs.pop('request')
    #     form = super().__init__(*args,**kwargs)
    #     form.fields['first_name']['placeholder']='First Name'
    # def clean(self):
    #     username = self.cleaned_data.get('username')
    #     password = self.cleaned_data.get('password')
    #
    #     user = authenticate(username=username,password=password)
    #     if user is not None:
    #         login(self.request,user)
    #     else:
    #         raise forms.ValidationError("The credentials is Invalid,please verify the Username or/and password")

src/accounts/api/views.py
from .serializers import  UserSerializer
from rest_framework.generics import ListAPIView
from rest_framework import permissions
from django.contrib.auth import  get_user_model


User = get_user_model()



class UsersSerializerListAPIView(ListAPIView):

    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


    def get_queryset(self):
        return User.objects.all()



# class WhoToFollowSerializerListAPIView(ListAPIView):
#
#     serializer_class = UserSerializer
#     permission_classes = [permissions.IsAuthenticated]
#
#
#     def get_queryset(self):
#         return User.objects.all()

src/accounts/views.py
from django.views.generic import CreateView,UpdateView,DetailView,View,ListView
from .forms import UserCreationForm,ProfileForm
from django.urls import reverse_lazy,reverse
from django.shortcuts import redirect,render
from django.contrib.auth import  get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from accounts.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from tweets.mixins import NextUrlMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.utils.html import mark_safe
from .models import Profile

User = get_user_model()


class GetAllUsers(ListView):
    model = User
    template_name = 'all_users.html'

    def get_queryset(self):
        return Profile.objects.\
            exclude(user__in=self.request.user.profile.get_following()).\
            exclude(id=self.request.user.id)


class CustomLoginView(NextUrlMixin,auth_views.LoginView):

    # def get_success_url(self):
    #     return redirect((super().get_success_url()))

    # def get_redirect_url(self):
    #     s = super().get_redirect_url()
    #     print(s)

    def form_invalid(self, form):
        return render(self.request,'all_tweets.html',{'loginform':form,'registerform':UserCreationForm})




class Register(SuccessMessageMixin,CreateView):

    form_class = UserCreationForm
    model = User
    template_name = 'registration.html'
    success_message = "%(username)s! your profile was created successfully, please login below to start Tweeting "

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            username=self.object.username.capitalize(),
        )


    def get_success_url(self):
        return reverse_lazy('tweets:all')


    def form_invalid(self, form):
        return render(self.request,'all_tweets.html',{'loginform':AuthenticationForm,'registerform':form})

class ProfileView(LoginRequiredMixin,DetailView):
    model = User
    template_name = 'registration/profile.html'


    # def get_queryset(self):
    #     user = User.objects.filter(slug=self.kwargs.get('slug'))
    #     tweets_qs = user.tweet_set.all()
    #     print(tweets_qs)
    #     return user




class UpdateProfileView(NextUrlMixin,LoginRequiredMixin,UpdateView):

    model = User
    form_class = ProfileForm
    template_name = 'registration/update_profile.html'


    # def get_success_url(self):
    #     if self.get_next_url():
    #         return self.get_next_url()
    #     return redirect(reverse('accounts:profile',kwargs={'slug':self.get_object().slug}))


    def get_initial(self):
        initial = super().get_initial()
        initial['date_of_birth'] = self.get_object().profile.date_of_birth
        initial['image'] = self.get_object().profile.image
        # print(self.get_object().profile.image)
        return initial


    def form_valid(self, form):
        print(form.cleaned_data)

        user=self.request.user
        try:
            profile_obj = user.profile
        except ObjectDoesNotExist:
            return super().form_invalid(form)
        if not form.cleaned_data.get('image'):
            profile_obj.image='mine/empty_pic.jpeg'
        else:
            profile_obj.image=form.cleaned_data.get('image')
        profile_obj.date_of_birth = form.cleaned_data.get('date_of_birth')
        profile_obj.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)




class ToggleFollow(LoginRequiredMixin,View):


    def dispatch(self, request, *args, **kwargs):
        user_obj = User.objects.get(slug=kwargs.get('slug'))
        if user_obj is not None:
            if user_obj in request.user.profile.get_following():
                request.user.profile.following.remove(user_obj)
            else:
                request.user.profile.following.add(user_obj)
        # return redirect(reverse('accounts:profile',kwargs={'slug':kwargs.get('slug')}))
        # return super().dispatch(request, *args, **kwargs)
        return redirect(request.META['HTTP_REFERER'])

src/accounts/templates/RecommendedUsers.html
{% load static %}
{% url 'accounts:all' as all_users %}
<ul style=" padding-left: 0px;padding-bottom: 3px;margin-bottom: 0px;">
    {% for profile in profile_qs %}
        <li class=" media border p-2 recommended"><a class="pull-left" href="/accounts/profile/{{ profile.user.slug }}/">
                    <img class="media-object rounded-circle d-flex align-self-start mr-3 img-fluid" alt="" style="width:60px" src="{% if profile.image %}{{ profile.image.url }}{% else %}{% static 'media/mine/empty_pic.jpeg' %}{% endif %}"></a>
                    <div class="media-body font-weight-bold">

                        <p class="media-heading font-weight-bold mr-2">

                            <span>
                                <a style="list-style-type:none;" id="LinkBlueColor"   href="/accounts/profile/{{ profile.user.slug }}/">{{ profile.user.username }}<i style="color: lightskyblue" class="pl-1 fa-sm fas fa-check-circle"></i></a><br>
                                <span style="color: grey" class="remove-decoration">@{{ profile.user.slug}}</span>
                            </span>
                            <a  style="width:100px;" role="button" href="{% url 'api-tweet:Follow' slug=profile.user.slug %}" id="FollowBtn" class="btn btn-light followbtn api-follow-btn ">Follow</a>
                        </p>

                    </div>
        </li>
    {% endfor %}
    <li class="text-center media border p-2 recommended">
                      <a class="mx-auto" href="{{ all_users  }}">see more</a>

    </li>
</ul>

src/accounts/templates/all_users.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="col-md-6">
            <h4 style="background-color: white" class="border mt-1 p-2">Who to follow</h4>

{#            {% include 'RecommendedUsers.html' with profile_qs=object_list %}#}
            <ul style=" padding-left: 0px;padding-bottom: 3px;margin-bottom: 0px;">
            {% for profile in object_list %}
                <li class=" media border p-2 recommended"><a class="pull-left" href="/accounts/profile/{{ profile.user.slug }}/">
                            <img class="media-object rounded-circle d-flex align-self-start mr-3 img-fluid" alt="" style="width:60px" src="{% if profile.image %}{{ profile.image.url }}{% else %}{% static 'media/mine/empty_pic.jpeg' %}{% endif %}"></a>
                            <div class="media-body font-weight-bold">

                                <p class="media-heading font-weight-bold mr-2">

                                    <span>
                                        <a style="list-style-type:none;" id="LinkBlueColor"   href="/accounts/profile/{{ profile.user.slug }}/">{{ profile.user.username }}<i style="color: lightskyblue" class="pl-1 fa-sm fas fa-check-circle"></i></a><br>
                                        <span style="color: grey" class="remove-decoration">@{{ profile.user.slug}}</span>
                                    </span>
                                    <a  style="width:100px;" role="button" href="{% url 'api-tweet:Follow' slug=profile.user.slug %}" id="FollowBtn" class="btn btn-light followbtn api-follow-btn ">Follow</a>
                                </p>

                            </div>
                </li>
            {% endfor %}

            </ul>
    </div>

{% endblock %}

src/accounts/templates/registration.html
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'tweets:all' as home_url%}

{% block content %}
<div   class="Login-register card mt-4  col-md-6 " style="margin-left: -85px;float: left;">
<article class="card-body">
    <span class="logo" ><i class="fab fa-lg fa-twitter">TweetMe</i></span>
	<h4 class="card-title mt-3 text-center">Create Account</h4>
	<p class="text-center">Get started with your free account</p>
	<p class="text-center">
		<a href="" id="btns-bg-color" class="btn btn-light"> <i style="color: white" class="fab fa-lg fa-facebook"></i>   Login via facebook</a>
	</p>
	<p  class="divider-text">
        <span  style="background-color: #CED4DA;" class="">OR</span>
    </p>
	<form class="pl-5 pr-5" method="post" action="{{ register_url }}"> {% csrf_token %}


        {{ form.non_field_errors }}

        {% crispy_addon form.username prepend="<span> <i class='fa fa-user'></i> </span>" form_show_labels=False %}

{#        {% crispy_addon form.first_name prepend="<span> <i class='fa fa-user'></i> </span>" form_show_labels=False %}#}
{##}
{#        {% crispy_addon form.last_name prepend="<span> <i class='fa fa-user'></i> </span>" form_show_labels=False %}#}

        {% crispy_addon form.email prepend="<span> <i class='fa fa-envelope'></i> </span>" form_show_labels=False %}

         {% crispy_addon form.password1 prepend="<span> <i class='fa fa-lock'></i> </span>" form_show_labels=False %}

        {% crispy_addon form.password2 prepend="<span> <i class='fa fa-lock'></i> </span>" form_show_labels=False %}


            <button type="submit" id="btns-bg-color" class="btn btn-light btn-block mx-auto"> Create Account  </button>
            {% include 'next_url.html' %}
        <p class="text-center">Have an account? <a href="{{ home_url }}">Log In</a> </p>
</form>
</article>
</div> <!-- card.// -->
{% endblock %}



{#    <div class="form-group input-group">#}
{#    	<div class="input-group-prepend">#}
{#		    <span class="input-group-text"> <i class="fa fa-phone"></i> </span>#}
{#		</div>#}
{#		<select class="custom-select" style="max-width: 120px;">#}
{#		    <option selected="">+965</option>#}
{#		    <option value="1">+972</option>#}
{#		    <option value="2">+198</option>#}
{#		    <option value="3">+701</option>#}
{#		</select>#}
{#    	<input name="" class="form-control" placeholder="Phone number" type="text">#}
{#    </div> <!-- form-group// -->#}