src/accounts/urls.py
from django.conf.urls import include,url
from .views import Register,ProfileView,ToggleFollow,UpdateProfileView,GetAllUsers
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy,reverse
from .views import CustomLoginView
app_name = 'accounts'

urlpatterns = [


   url(r'related_users/$', GetAllUsers.as_view(),name='all'),
   url(r'profile/(?P<slug>[\w.@+-]+)/$', ProfileView.as_view(),name='profile'),
   url(r'profile/(?P<slug>[\w.@+-]+)/update$', UpdateProfileView.as_view(),name='update_profile'),
   url(r'profile/follow/(?P<slug>[\w.@+-]+)$', ToggleFollow.as_view(), name='Follow'),

   url('register/',Register.as_view(),name='register'),
   url('login/', CustomLoginView.as_view(),name='login'),




   url('logout/', auth_views.LogoutView.as_view(), name='logout'),

   url('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),

   url('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),


]

src/tweetme/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('admin/', admin.site.urls),



    url('^',include('tweets.urls', namespace='tweets')),




    url('^api/tweet/',include('tweets.api.urls', namespace='api-tweet')),

    url('^api/accounts/',include('accounts.api.urls', namespace='api-accounts')),

    url('^api/tags/',include('Hashtag.api.urls', namespace='api-tags')),


    url('^accounts/',include('accounts.urls', namespace='accounts')),


    url('^accounts/',include('accounts.password.urls')),
    url('^tags/', include('Hashtag.urls', namespace='#tags')),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tweets/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from .views import GetTweet,DetailTweet,CreateTweet,SearchTweet,DeleteTweet,UpdateTweet,Retweet


app_name="tweets"

urlpatterns = [

    url(r'^$',GetTweet.as_view(),name='all'),
    url(r'^tweet/(?P<pk>\d+)/$',DetailTweet.as_view(),name='detail'),
    url(r'^tweet/create/$',CreateTweet.as_view(),name='create'),
    url(r'^tweet/delete/(?P<pk>\d+)/$',DeleteTweet.as_view(),name='delete'),
    url(r'^tweet/update/(?P<pk>\d+)/$',UpdateTweet.as_view(),name='update'),
    url(r'^tweet/search/$',SearchTweet.as_view(),name='search'),

    url(r'^tweet/(?P<pk>\d+)/retweet$', Retweet.as_view(), name='retweet'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/tweetme/templates/LeftSideBar.html
{% load static %}
{% url 'accounts:profile' slug=user.slug as profile_url %}
{% url 'tweets:all' as home_url %}
{%  url '#tags:all' as all_tags %}

<div class="page-wrapper chiller-theme toggled">

  <a id="show-sidebar" class="btn btn-sm btn-light" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">

      <div class="sidebar-header">

        <a href="{{ profile_url }}" class="user-pic">
          <img class="img-responsive img-rounded" src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static 'media/mine/empty_pic.jpeg' %}{% endif %}"
{#                  "https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"#}
            alt="User picture">
        </a>
        <div class="user-info">
          <span class="user-name"><strong>{% if user.first_name and user.last_name%}{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}{% else %}{{ user.username|capfirst }} {% endif %}</strong>
          </span>
          <span class="user-role">Software Developer</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
        <div class="sidebar-brand">

            <div id="close-sidebar">
              <i class="fas fa-times"></i>
            </div>
          </div>
      </div>
      <!-- sidebar-header  -->


      <div class="sidebar-menu">
        <ul>

          <li>
            <a href="{{ home_url }}">
              <i class="fas fa-home"></i>
              <span>Home</span>
            </a>
          </li>
          <li>
            <a  href="{{ all_tags }}">
             <i class="fas fa-hashtag"></i>
              <span>Hashtags</span>
            </a>
          </li>
            <li>
            <a href="#">
             <i class="far fa-bell"></i>
              <span>Notifications</span>
            </a>
          </li>
            <li>
            <a href="#">
             <i class="far fa-envelope"></i>
              <span>Messages</span>
            </a>
          </li>
            <li>
            <a href="{{ profile_url }}">
              <i class="far fa-user-circle"></i>
              <span>profile</span>
            </a>
          </li>

            <li class="sidebar-li-Tweetbtn">
                <a  class='sidebar-Tweetbtn btn btn-sm btn-light ml-5'  href='#'>
                    <i class="fab fa-lg fa-twitter"> </i>
                      <span>Tweet</span>
                </a>
            </li>



        </ul>

      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->


    <div class="sidebar-footer">
      <a href="https://www.facebook.com/hossam.elneily">
        <i class="fab  fa-lg fa-facebook"> </i>
      </a>
      <a href="https://twitter.com/HElneily">
       <i class="fab fa-lg fa-twitter"> </i>
      </a>
      <a href="www.linkedin.com/in/hossam-elneily">
        <i class="fab fa-lg fa-linkedin"> </i>
      </a>
      <a href="https://github.com/hossamelneily">
        <i class="fab fa-lg  fa-github"></i>
      </a>

    </div>





  </nav>
  <!-- sidebar-wrapper  -->

</div>

    

src/tweetme/templates/RightSideBar.html
{% load static %}
{% url 'accounts:profile' slug=user.slug as profile_url %}
{% url 'tweets:all' as home_url %}

{% load recommended_users %}
{% load recommended_tags %}



<div class="chiller-theme">

                                        <!-- Trends side part -->

  <nav id="sidebar" class="sidebar-wrapper-part2" >
    <div class="sidebar-content-trends">

        <div class="sidebar-header">
            <strong>Trends for you</strong>
                <a class="sidebar-brand dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-cog"></i>

                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
        </div>

      <!-- sidebar-header  -->


      <div class="sidebar-menu">
          {% recommended_tags %}
      </div>
      <!-- sidebar-menu  -->

    </div>

                                        <!-- Followers side part -->
    <div class="sidebar-content-follow">


      <!-- sidebar-header  -->



          <div class="sidebar-header">
                <strong>Who to follow</strong>
                <a class="sidebar-brand dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-cog"></i>

                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
          </div>



         <div class="sidebar-menu">

            {% recommended_users user %}

         </div>
      <!-- sidebar-menu  -->
    </div>
      <div class="sidebar-content-info">


         <div class="sidebar-menu">
                <a class="mr-3 pl-2" id="" href="" >Terms</a>
                 <a class="mr-3" id="" href="" >Privacy policy</a>
                 <a class="mr-3" id="" href="" >Cookies</a>
                <a class="mr-3" id="" href="" >Ads info</a>
{#                <a class="mr-3" id="" href="" >More</a>#}
                <a class="pl-5" id="" href="" >© 2019 copywrite, HossamElNeily.</a>

         </div>
      <!-- sidebar-menu  -->
    </div>
        <!-- sidebar-content  -->
    <!-- sidebar-content  -->
  </nav>
</div>


    

src/tweetme/templates/about.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
         <div class="text-center">
             <h2>{{ template_name }}</h2>
         </div>

    </div>

{% endblock %}

src/tweetme/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TweetMe {% block title %}{% endblock title %}</title>

    <link href="{% static 'mine/css/custom.css' %}" rel="stylesheet">
{#    <link href="{% static 'bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">#}
    <link href="{% static 'fontawesome/dist/css/all.css' %}" rel="stylesheet">



    <script  language="JavaScript" type="text/javascript" src="{% static 'jquery/jquery-3.4.1.min.js' %}" ></script>
{#    <script src="{% static 'bootstrap/dist/js/bootstrap.js' %}" ></script>#}





    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



    <script language="JavaScript" type="text/javascript" src="{% static 'mine/js/custom.js' %}" ></script>
    {% block script %}{% endblock %}
    <script> empty_img = '{% static 'media/mine/empty_pic.jpeg' %}'
            {#Login_user = {{ request.user }}#}
    </script>
</head>
<body style="background: url('{% static 'media/mine/bk_2.jpg' %}')">


    {% include 'navbar.html' %}
    {% include 'ReplyModal.html' %}

    <div class="container">

        <div class="row">

                <div class="col-md-3">
                    {% if request.user.is_authenticated %}
                        {% include 'LeftSideBar.html' %}
                    {% endif %}
                </div>

                {% block content %}
                {% endblock %}
                <div class="col-md-3">
                    {% if request.user.is_authenticated %}
                        {% include 'RightSideBar.html' %}
                    {% endif %}
                </div>
        </div>

    </div>


{#    {% include 'footer.html' %}#}

</body>


</html>

src/tweetme/templates/contact.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <p>

                </p>
                <div class="col-sm-6 col-12 mx-auto">
                  <form class="contact-form" method="post" action="{% url "contact" %}"> {% csrf_token %}
                     {{ form.as_p }}
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
{#                                <form method="post"> {% csrf_token %}#}
{#                                    <input type="text" class="form-control" placeholder="Name" name="fullname">#}
{#                                    <input type="text" class="form-control" placeholder="email" name="email">#}
{#                                    <textarea name="content" class="form-control" placeholder="your content"></textarea>#}
{#                                    <button type="submit" class="btn btn-default">Submit</button>#}
{#                                </form>#}
                </div>
            </div>
        </div>

        <ul class="list-group">

        </ul>
    </div>
{% endblock %}

src/tweetme/templates/footer.html
<!-- Footer -->
<footer class="font-small bg-light navbar-fixed-bottomt">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center pt-3">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab  fa-lg fa-facebook"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-lg fa-twitter"> </i>
        </a>
      </li>

      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-lg fa-linkedin"> </i>
        </a>
      </li>

    </ul>
    <!-- Social buttons -->


  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-1">© 2019 Copyright:Made by Hossam ElNeily.

  </div>
  <!-- Copyright -->
    </div>
</footer>
<!-- Footer -->

src/tweetme/templates/messages.html
{% load static %}
{#{% if messages %}#}
{#<ul class="messagelist">#}
{#    {% for message in messages %}#}
{#    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
{#        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}#}
{#        {{ message }}#}
{#    </li>#}
{#    {% endfor %}#}
{#</ul>#}
{#{% endif %}#}

{% if messages %}
        <div class="alert alert-success messages">
            {% for message in messages %}
            <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                <img src="{% static 'admin/img/icon-yes.svg' %}">
                {{ message|safe }}
                <i class="fab fa-twitter"> </i>
                <a href="#" class="float-right del-msg"><i class="fas fa-times"></i></a>
            </span>

            {% endfor %}
        </div>
{% endif %}

{#{% if messages %}#}
{#<ul class="messages">#}
{#    {% for message in messages %}#}
{#    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
{#        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}#}
{#        {{ message }}#}
{#    </li>#}
{#    {% endfor %}#}
{#</ul>#}
{#{% endif %}#}
{#{% if messages %}#}
{#<ul  class="messagelist">#}
{#    {% for message in messages %}#}
{#    <li class="{{ message.tags }}">#}
{#        {% if 'safe' in message.tags %}#}
{#            {{ message|safe }}#}
{#        {% else %}#}
{#            {{ message }}#}
{#        {% endif %}#}
{#    </li>#}
{#    {% endfor %}#}
{#</ul>#}
{#{% endif %}#}
{##}
{#{% if messages %}#}
{#        <ul class="messagelist">#}
{#            {% for message in messages %}#}
{#                <li{% if message.tags %} class="{{ message.tags }}"#}
{#                {% endif %}>#}
{#                    {{ message}}#}
{#                </li>#}
{#            {% endfor %}</ul>#}
{#{% endif %}#}

src/tweetme/templates/navbar.html
{% url 'tweets:search' as search_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:profile'  slug=request.user.slug as profile_url %}
{% url 'tweets:all' as home_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{#style="width: 75%;" {% if request.user.is_authenticated %}  {% endif %}#}
<nav class="navbar sticky-top navbar-expand-lg navbar-light" >
    <div class="container">
  <a class="navbar-brand" href="{{ home_url }}">
    <i class="fab  fa-lg fa-twitter"></i> TweetMe
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if request.user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{{ home_url }}">{{ request.user.username }}'s Home  <span class="sr-only">(current)</span></a>
              </li>
            </ul>

            {% include 'forms/search_form.html' %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-lg fa-caret-down"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{ profile_url }}">Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ logout_url }}"><i class="fas fa-sign-out-alt"></i>Logout</a>
                </div>
              </li>

        </ul>
   {% else %}
{#        <ul class="navbar-nav  ml-auto">#}
{##}
{#            <li class="nav-item active">#}
{#                 <a class="nav-link" href="{{ login_url }}">Login <span class="sr-only">(current)</span></a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                 <a class="nav-link" href="{{ register_url }}">Register  </a>#}
{#            </li>#}
{##}
{#        </ul>#}

  {% endif %}

  </div>
        </div>
</nav>

src/tweetme/templates/next_url.html
{% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
{% endif %}