src/tweetme/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('admin/', admin.site.urls),



    url('^',include('tweets.urls', namespace='tweets')),




    url('^api/tweet/',include('tweets.api.urls', namespace='api-tweet')),

    url('^api/accounts/',include('accounts.api.urls', namespace='api-accounts')),

    url('^api/tags/',include('Hashtag.api.urls', namespace='api-tags')),


    url('^accounts/',include('accounts.urls', namespace='accounts')),


    url('^accounts/',include('accounts.password.urls')),
    url('^tags/', include('Hashtag.urls', namespace='#tags')),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tweets/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from .views import GetTweet,DetailTweet,CreateTweet,SearchTweet,DeleteTweet,UpdateTweet,Retweet


app_name="tweets"

urlpatterns = [

    url(r'^$',GetTweet.as_view(),name='all'),
    url(r'^tweet/(?P<pk>\d+)/$',DetailTweet.as_view(),name='detail'),
    url(r'^tweet/create/$',CreateTweet.as_view(),name='create'),
    url(r'^tweet/delete/(?P<pk>\d+)/$',DeleteTweet.as_view(),name='delete'),
    url(r'^tweet/update/(?P<pk>\d+)/$',UpdateTweet.as_view(),name='update'),
    url(r'^tweet/search/$',SearchTweet.as_view(),name='search'),

    url(r'^tweet/(?P<pk>\d+)/retweet$', Retweet.as_view(), name='retweet'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/tweetme/templates/forms/search_form.html
{% url 'api-tweet:search' as api_search_url %}
{% url 'tweets:search' as search_url %}

<form   id="search-form" class="form-inline navbar-search" method="GET" action="{{ search_url }}" data-url="{{ api_search_url }}">

        <div class="form-group">
            <span class="fa fa-search search-icon"></span>
            <input type="submit" style="display: none" />
            <input type="search" class="form-control py-2 border-right-0 border search_query" placeholder="Search" name="q" value="{{ request.GET.q }}" aria-label="Search">
        </div>
</form>