src/accounts/urls.py
from django.conf.urls import include,url
from .views import Register,ProfileView,ToggleFollow,UpdateProfileView,GetAllUsers
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy,reverse
from .views import CustomLoginView
app_name = 'accounts'

urlpatterns = [


   url(r'related_users/$', GetAllUsers.as_view(),name='all'),
   url(r'profile/(?P<slug>[\w.@+-]+)/$', ProfileView.as_view(),name='profile'),
   url(r'profile/(?P<slug>[\w.@+-]+)/update$', UpdateProfileView.as_view(),name='update_profile'),
   url(r'profile/follow/(?P<slug>[\w.@+-]+)$', ToggleFollow.as_view(), name='Follow'),

   url('register/',Register.as_view(),name='register'),
   url('login/', CustomLoginView.as_view(),name='login'),




   url('logout/', auth_views.LogoutView.as_view(), name='logout'),

   url('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),

   url('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),


]

src/tweetme/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('admin/', admin.site.urls),



    url('^',include('tweets.urls', namespace='tweets')),




    url('^api/tweet/',include('tweets.api.urls', namespace='api-tweet')),

    url('^api/accounts/',include('accounts.api.urls', namespace='api-accounts')),

    url('^api/tags/',include('Hashtag.api.urls', namespace='api-tags')),


    url('^accounts/',include('accounts.urls', namespace='accounts')),


    url('^accounts/',include('accounts.password.urls')),
    url('^tags/', include('Hashtag.urls', namespace='#tags')),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tweets/api/urls.py
from django.conf.urls import url
from .views import TweetSerializerListAPIView,\
    TweetSerializerCreateAPIView,LikesTweetsAPIView,\
    TweetSerializerDetailAPIView,FollowTweetsAPIView,RetweetTweetsAPIView

app_name="api"

urlpatterns = [


    ##api serializer
    url(r'^$', TweetSerializerListAPIView.as_view(), name='all'),
    url(r'^(?P<pk>\d+)/$', TweetSerializerDetailAPIView.as_view(), name='detail'),
    url(r'^search/$', TweetSerializerListAPIView.as_view(), name='search'),
    url(r'^create/$', TweetSerializerCreateAPIView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w.@+-]+)/$', TweetSerializerListAPIView.as_view(), name='profile'),
    # url(r'^users/$', UsersSerializerListAPIView.as_view(), name='all-users'),
    url(r'^(?P<id>\d+)/like$', LikesTweetsAPIView.as_view(), name='tweet-likes'),
    url(r'follow/(?P<slug>[\w.@+-]+)$', FollowTweetsAPIView.as_view(), name='Follow'),
    url(r'^(?P<pk>\d+)/retweet$', RetweetTweetsAPIView.as_view(), name='retweet'),
]

src/tweets/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from .views import GetTweet,DetailTweet,CreateTweet,SearchTweet,DeleteTweet,UpdateTweet,Retweet


app_name="tweets"

urlpatterns = [

    url(r'^$',GetTweet.as_view(),name='all'),
    url(r'^tweet/(?P<pk>\d+)/$',DetailTweet.as_view(),name='detail'),
    url(r'^tweet/create/$',CreateTweet.as_view(),name='create'),
    url(r'^tweet/delete/(?P<pk>\d+)/$',DeleteTweet.as_view(),name='delete'),
    url(r'^tweet/update/(?P<pk>\d+)/$',UpdateTweet.as_view(),name='update'),
    url(r'^tweet/search/$',SearchTweet.as_view(),name='search'),

    url(r'^tweet/(?P<pk>\d+)/retweet$', Retweet.as_view(), name='retweet'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/tweets/forms.py
from django import forms
from django.contrib.auth import authenticate , login , get_user_model
from .models import Tweet

class TweetForm(forms.ModelForm):


    class Meta:
        model = Tweet
        fields = ['content']
        labels = {
            'content':''
        }

        widgets= {
            'content':forms.Textarea(attrs={'placeholder': 'what\'s in your mind','class':'form-control','id':'TweetTA'}),
        }
        error_messages ={

            'content':{
                'max_length': 'The body of a link post can have at most 10 characters',
            }
        }

    def __init__(self, *args, **kwargs):
        # self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.fields['content'].error_messages = {'max_length': 'Please let us know what to call you!'}



    # def save(self, commit=True):
    #     instance = super().save(commit=False)
    #     print(instance)
    #     if self.request.user:
    #         instance.user=self.request.user
    #     instance.save()
    #     return instance

src/tweets/api/views.py
from .serializers import TweetSerializer, UserSerializer
from rest_framework.generics import ListAPIView,CreateAPIView,ListCreateAPIView,RetrieveAPIView
from rest_framework.views import APIView
from ..models import Tweet
from rest_framework import permissions
from .pagination import LargeResultsSetPagination
from django.contrib.auth import  get_user_model
import re
from Hashtag.models import hashtag
from rest_framework.response import Response
from django.http import JsonResponse
from rest_framework.exceptions import APIException
from rest_framework.renderers import JSONRenderer
from rest_framework import status
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse_lazy,reverse


User = get_user_model()

class TweetSerializerListAPIView(ListAPIView):

    serializer_class = TweetSerializer
    permission_classes = [permissions.IsAuthenticated]
    pagination_class = LargeResultsSetPagination

    def get_queryset(self):  #this get_queryset is called twice
        print("from ajax call")
        if self.kwargs.get('slug') is not None:
            my_tweets = Tweet.objects.filter(user__slug=self.kwargs.get('slug'))
            # user_obj = User.objects.get(slug=self.kwargs.get('slug'))
            # wd=User.objects.all()
            # my_tweets = user_obj.tweet_set.all().order_by('-timestamp') #this will the all() of accounts.profile which is wrong
            return my_tweets

        elif self.kwargs.get('tag_name') is not None:
            tag_name = self.kwargs.get('tag_name')
            hash_tweets = Tweet.objects.search('#'+tag_name)
            return hash_tweets

        elif self.request.GET.get('q') is not None:     # if there is query to be searched for
            # print(self.request.GET.get('q'))
            return Tweet.objects.search(self.request.GET.get('q'))

        else:                                   # if list all the tweets
            qs = Tweet.objects.filter(user__in=self.request.user.profile.get_following())
            my_tweets = self.request.user.tweet_set.all()
            qs =  (qs | my_tweets).distinct().order_by('-timestamp')
            print(qs)
            return qs


class TweetSerializerDetailAPIView(ListAPIView):
    serializer_class = TweetSerializer
    permission_classes = [permissions.IsAuthenticated]

    # queryset = Tweet.objects.all()
    def get_queryset(self):

        if self.kwargs.get('pk') is not None:
            tweet_qs = Tweet.objects.filter(pk=self.kwargs.get('pk'))
            tweet_obj = tweet_qs.first()

            if tweet_obj.parent:
                parent_id = tweet_obj.parent.id
                parent_qs = Tweet.objects.filter(id=parent_id)
                children_qs = parent_qs.first().tweet_set.all().order_by('timestamp')
                result_qs = (children_qs | parent_qs).distinct()
            else:
                result_qs = tweet_qs
            # print(tweet_obj)
            # print(children_qs)

            return result_qs

class TweetSerializerCreateAPIView(CreateAPIView):
    serializer_class = TweetSerializer
    permission_classes = [permissions.IsAuthenticated]


    def perform_create(self, serializer):
        request = self.request
        serializer.save(user=request.user)
        for tag in re.findall('#([\w\d-]+)', request.data.get('content')):
            print(tag)
            obj, created = hashtag.objects.get_or_create(tag='#' + tag)
            obj.count=obj.count+1
            obj.save()

        print("Create API view")
        # print(request.data.get('parent_id'))
        if(request.data.get('isreply')):
            serializer.save(Reply=True)



class LikesTweetsAPIView(APIView):

    permission_classes = [permissions.IsAuthenticated]

    def dispatch(self, request, *args, **kwargs):
        print('like api call ')
        tweet_obj = Tweet.objects.get(id=kwargs.get('id'))
        if tweet_obj is not None:
             print(tweet_obj.id)
             liked,likes_count,parent_object_id,parent_likes_count =Tweet.objects.Liked(request.user,tweet_obj)
             response = Response(
                 {"liked": liked,'likes_count':likes_count,'parent_object_id':parent_object_id,'parent_likes_count':parent_likes_count},
                 content_type="application/json",
             )
             response.accepted_renderer = JSONRenderer()
             response.accepted_media_type = "application/json"
             response.renderer_context = {}
             return response
        raise APIException({'message':"Error in Like API function"})


class RetweetTweetsAPIView(APIView):

    permission_classes = [permissions.IsAuthenticated]

    def dispatch(self, request, *args, **kwargs):
        print('retweet api call ')
        tweet_obj = Tweet.objects.get(id=kwargs.get('pk'))
        if tweet_obj is not None:
             new_tweet =Tweet.objects.retweet(request.user,tweet_obj)
             return HttpResponseRedirect(reverse('tweets:all'))
        raise APIException({'message':"Error in Retweet API function"})


class FollowTweetsAPIView(APIView):

    permission_classes = [permissions.IsAuthenticated]

    def dispatch(self, request, *args, **kwargs):
        user_obj = User.objects.get(slug=kwargs.get('slug'))
        if user_obj is not None:
            if user_obj in request.user.profile.get_following():
                request.user.profile.following.remove(user_obj)
                follow=False
            else:
                request.user.profile.following.add(user_obj)
                follow=True
        print('follow with ajax call')
        following_count = user_obj.profile.get_following().all().count()
        followers_count=  user_obj.followed_by.all().count()
        return JsonResponse({"following_count": following_count, 'followers_count': followers_count,'follow':follow})

src/tweets/views.py
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView,View,TemplateView
from .models import Tweet
from .forms import TweetForm
from django.urls import reverse_lazy,reverse
from django.shortcuts import redirect,HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q
from Hashtag.models import hashtag
from django.shortcuts import render
from django.contrib.auth import  get_user_model


User = get_user_model()
class GetTweet(ListView):     # this is not working as i modified on the all_tweets html
    model = Tweet
    template_name = 'all_tweets.html'


    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['create_form'] = TweetForm()
        context['include_url'] = reverse('tweets:create')
        context['btn_title'] = 'Tweet'
        context['registerform'] = UserCreationForm
        context['loginform'] = AuthenticationForm
        return context






class DetailTweet(LoginRequiredMixin,DetailView):
    model = Tweet
    template_name = 'detail_tweet.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # print(context)
        return context

class CreateTweet(LoginRequiredMixin,CreateView):
    form_class = TweetForm
    template_name = 'all_tweets.html'
    success_url = reverse_lazy('tweets:all')

    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['create_form'] = TweetForm()
        context['include_url'] = reverse('tweets:create')
        context['btn_title'] = 'Tweet'
        return context

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user

        # if form.instance.content  is not None:
        #     form.instance.content
        return super().form_valid(form)




class UpdateTweet(LoginRequiredMixin,UpdateView):
    form_class = TweetForm
    model = Tweet
    template_name = 'generic_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['btn-value'] = 'Update'
        return context




class DeleteTweet(LoginRequiredMixin,DeleteView):
    model = Tweet
    success_message = "Deleted Successfully"
    success_url = reverse_lazy('tweets:all')

    template_name = 'form_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['btn-value'] = 'Delete'
        return context




# search form CBV
class SearchTweet(LoginRequiredMixin,View):


    def dispatch(self, request, *args, **kwargs):
        query = request.GET.get('q')

        if query and len(query.strip()):
            # print(query)
            query = query.strip()
            lookup_users = Q(username__icontains=query) | Q(email__icontains=query)
            users_qs_search = User.objects.filter(lookup_users).distinct()


            tags_qs_search = hashtag.objects.filter(tag__icontains='#'+query)

            if users_qs_search.exists() or tags_qs_search.exists():
                # print(tags_qs_search)
                return render(request,'search_tweets.html',{'users_qs_search':users_qs_search,'tags_qs_search':tags_qs_search})
            else:
                return render(request,'search_tweets.html',{})

        else:
            return render(request,'search_tweets.html',{})





class Retweet(LoginRequiredMixin,View):
    def dispatch(self, request, *args, **kwargs):
        parent_tweet_obj = Tweet.objects.get(pk=kwargs.get('pk'))
        child_tweet_obj = Tweet.objects.retweet(request.user,parent_tweet_obj)
        return redirect(reverse('tweets:all'))

class LikeTweet(View):
    def dispatch(self, request, *args, **kwargs):
        tweet_obj = Tweet.objects.get(id=kwargs.get('id'))
        if tweet_obj is not None:
            Tweet.objects.Liked(request.user,tweet_obj)
        return redirect(reverse('tweets:all'))

src/tweets/templates/LeftSideBar.html
{% load static %}
{% url 'accounts:profile' slug=user.slug as profile_url %}
{% url 'tweets:all' as home_url %}

<div class="page-wrapper chiller-theme toggled">

  <a id="show-sidebar" class="btn btn-sm btn-light" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">

      <div class="sidebar-header">

        <a href="{{ profile_url }}" class="user-pic">
          <img class="img-responsive img-rounded" src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static 'media/mine/empty_pic.jpeg' %}{% endif %}"
{#                  "https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"#}
            alt="User picture">
        </a>
        <div class="user-info">
          <span class="user-name"><strong>{{ user.first_name|capfirst }}
            {{ user.last_name|capfirst }}</strong>
          </span>
          <span class="user-role">Software Developer</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
        <div class="sidebar-brand">

            <div id="close-sidebar">
              <i class="fas fa-times"></i>
            </div>
          </div>
      </div>
      <!-- sidebar-header  -->


      <div class="sidebar-menu">
        <ul>

          <li>
            <a href="{{ home_url }}">
              <i class="fas fa-home"></i>
              <span>Home</span>
            </a>
          </li>
          <li>
            <a href="#">
             <i class="fas fa-hashtag"></i>
              <span>Hashtags</span>
            </a>
          </li>
            <li>
            <a href="#">
             <i class="far fa-bell"></i>
              <span>Notifications</span>
            </a>
          </li>
            <li>
            <a href="#">
             <i class="far fa-envelope"></i>
              <span>Messages</span>
            </a>
          </li>
            <li>
            <a href="{{ profile_url }}">
              <i class="far fa-user-circle"></i>
              <span>profile</span>
            </a>
          </li>

            <li class="sidebar-li-Tweetbtn">
                <a  class='sidebar-Tweetbtn btn btn-sm btn-light ml-5'  href='#'>
                    <i class="fab fa-lg fa-twitter"> </i>
                      <span>Tweet</span>
                </a>
            </li>



        </ul>

      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->


    <div class="sidebar-footer">
      <a href="https://www.facebook.com/hossam.elneily">
        <i class="fab  fa-lg fa-facebook"> </i>
      </a>
      <a href="https://twitter.com/HElneily">
       <i class="fab fa-lg fa-twitter"> </i>
      </a>
      <a href="www.linkedin.com/in/hossam-elneily">
        <i class="fab fa-lg fa-linkedin"> </i>
      </a>
      <a href="https://github.com/hossamelneily">
        <i class="fab fa-lg  fa-github"></i>
      </a>

    </div>





  </nav>
  <!-- sidebar-wrapper  -->

</div>

    

src/tweets/templates/RightSideBar.html
{% load static %}
{% url 'accounts:profile' slug=user.slug as profile_url %}
{% url 'tweets:all' as home_url %}
{% load recommended_users %}
{% load recommended_tags %}



<div class="chiller-theme">

                                        <!-- Trends side part -->

  <nav id="sidebar" class="sidebar-wrapper-part2" >
    <div class="sidebar-content-trends">

        <div class="sidebar-header">
            <strong>Trends for you</strong>
                <a class="sidebar-brand dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-cog"></i>

                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
        </div>

      <!-- sidebar-header  -->


      <div class="sidebar-menu">
          {% recommended_tags %}
      </div>
      <!-- sidebar-menu  -->

    </div>

                                        <!-- Followers side part -->
    <div class="sidebar-content-follow">


      <!-- sidebar-header  -->



          <div class="sidebar-header">
                <strong>Who to follow</strong>
                <a class="sidebar-brand dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-cog"></i>

                </a>

                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
          </div>



         <div class="sidebar-menu">

            {% recommended_users user %}

         </div>
      <!-- sidebar-menu  -->
    </div>
      <div class="sidebar-content-info">


         <div class="sidebar-menu">
                <a class="mr-3 pl-2" id="" href="" >Terms</a>
                 <a class="mr-3" id="" href="" >Privacy policy</a>
                 <a class="mr-3" id="" href="" >Cookies</a>
                <a class="mr-3" id="" href="" >Ads info</a>
{#                <a class="mr-3" id="" href="" >More</a>#}
                <a class="pl-5" id="" href="" >© 2019 copywrite, HossamElNeily.</a>

         </div>
      <!-- sidebar-menu  -->
    </div>
        <!-- sidebar-content  -->
    <!-- sidebar-content  -->
  </nav>
</div>


    

src/tweets/templates/search_tweets.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="bs-example mx-auto col-md-6">
    <h4 class="mt-3">Search Results</h4>

    <ul class="nav nav-tabs pt-2">

        <li class="nav-item">
            <a id="btns-bg-color" style="width: auto" href="#tweets" class="nav-link active mr-3" data-toggle="tab">Tweets</a>
        </li>
        <li class="nav-item">
            <a id="btns-bg-color" style="width: auto" href="#people" class="nav-link mr-3" data-toggle="tab">People</a>
        </li>

        <li class="nav-item">
            <a id="btns-bg-color" style="width: auto" href="#tags" class="nav-link" data-toggle="tab">Hashtags</a>
        </li>

    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="tweets">
            <h3 class="mt-2">Tweets tab content</h3>
            <ul id="IdMedia">
            </ul>
        </div>
        <div class="tab-pane fade" id="people">
            <h3 class="mt-2">people tab content</h3>

            <ul id="IdMedia-users">
                {% for user in users_qs_search %}
                    <li class="media"><a class="pull-left profile-view" href="/accounts/profile/{{ user.slug }}/">
                    <img class="media-object rounded-circle d-flex align-self-start mr-3 img-fluid" alt="" style="width:60px" src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static 'media/mine/empty_pic.jpeg' %}{% endif %}"></a>
                    <div class="media-body ">
                        <p class="media-heading font-weight-bold">
                            <a id="LinkBlueColor"  href="/accounts/profile/{{ user.slug }}/">{{ user.username }}</a>
                            {% if user != request.user %}
                                {% if user in  request.user.profile.get_following.all%}
                                            <a  style="float: right" role="button" href="{% url 'api-tweet:Follow' slug=user.slug %}" id="FollowBtn" class="btn btn-light unfollowbtn api-follow-btn"><span>Following</span></a>
                                            {% else %}
                                             <a   style="float: right" role="button" href="{% url 'api-tweet:Follow' slug=user.slug %}" id="FollowBtn" class="btn btn-light followbtn api-follow-btn">Follow</a>
                                {% endif %}
                            {% endif %}
                        </p>

                    </div>
                    </li>


                {% empty %}
                    <li class="lead">Sorry, no users found.</li>
                {% endfor %}
            </ul>



        </div>
        <div class="tab-pane fade show" id="tags">
            <h3 class="mt-2">tags tab content</h3>
            <ul id="IdMedia-tags">
                {% for tag in tags_qs_search %}

                  <li><a href="{% url '#tags:tweets' tag_name=tag.tag|slice:"1:" %}">{{ tag }}</a></li>

                {% empty %}
                    <li class="lead">Sorry, no hashtags found.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}



    <li class="media"><a class="pull-left profile-view" href="/accounts/profile/flupper/">
        <img class="media-object rounded-circle d-flex align-self-start mr-3 img-fluid" alt="" style="width:60px" src="http://127.0.0.1:8000/media/user_1/7069126721492718354.jpg"></a>
        <div class="media-body ">
            <p class="mt-0 media-heading font-weight-bold">
                <a id="LinkBlueColor" class="profile-view" href="/accounts/profile/flupper/">Hossy</a>
                <br>
            </p>
        </div>
    </li>

src/tweets/templates/user_details.html
{% load  static %}
{% url 'accounts:update_profile' slug=user.slug as update_profile %}
<div style="background-color: rgba(255,255,255,0.83);" class="card text-dark user-details">

    <div class="card-body cd-bd">
            <div class="row">
                <div class="col-md-12 ">

                        <a class="" href="#">
                            <img class="media-object rounded-circle" src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static 'media/mine/empty_pic.jpeg' %}{% endif %}" style="width: 100px;height:100px;">
                        </a>

                        {% if request.user == object %}
                            <a  role="button" href="{{ update_profile }}"  class="btn btn-light Editbtn">Edit profile</a>
                            {% else %}
                                {% if object in  request.user.profile.get_following.all%}
                                    <a  role="button" href="{% url 'api-tweet:Follow' slug=object.slug %}" id="FollowBtn" class="btn btn-light unfollowbtn api-follow-btn"><span>Following</span></a>
                                    {% else %}
                                     <a   role="button" href="{% url 'api-tweet:Follow' slug=object.slug %}" id="FollowBtn" class="btn btn-light followbtn api-follow-btn">Follow</a>
                                {% endif %}

                        {% endif %}

                </div>
                <div class="col-md-12">

                    <span id="LinkBlueColor" style="font-size: larger;font-weight: bold">{% if user.first_name and user.last_name%}{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}{% else %}{{ user.username|capfirst }} {% endif %} </span><br>
                    <span style="color: grey" class="remove-decoration">@{{ user.slug}}</span><br>
                    <span class="remove-decoration"><i class="fas fa-briefcase"></i> Software Developer at Itlogiakuwait</span>
                    <span style="float: right">
                        <a href="#" class="remove-decoration"><strong class="following"> {{ object.profile.get_following.all.count }} Following</strong></a>
                        <a href="#" class="remove-decoration"><strong class="unfollow"> {{ object.followed_by.all.count }} Followers</strong></a>
                    </span><br>
                    <span><a  href="#" class="remove-decoration"><i class="fas fa-envelope"></i> {{ user.email }}</a></span>
                    <span style="float: right;margin-right: 38px" href="#" class="remove-decoration"> <i class="fas fa-mobile"></i> +965 94720613</span><br>


                    <span href="#" class="remove-decoration"> <i class="far fa-clock"></i> Joined {{ user.profile.date_joined|date:'F Y' }}</span>



                    <span style="float: right"href="" target="_blank" class="remove-decoration"><i class="fas fa-map-marker-alt"></i> from Egypt,Alexandria</span>
                </div>
            </div>
    </div>


{#    <div id="IdFooter" class="card-footer" >#}
{#        <ul class="social-network social-circle">#}
{#            <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>#}
{#            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fab fa-facebook"></i></a></li>#}
{#            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fab fa-twitter"></i></a></li>#}
{#            <li><a href="#" class="icoGoogle" title="Google +"><i class="fab fa-google-plus"></i></a></li>#}
{#            <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fab fa-linkedin"></i></a></li>#}
{#        </ul>#}
{#    </div>#}
{#    <button class="btn btn-light" style="background-color: lightskyblue" id="Editbtn">Edit Profile</button>#}
<!-- <div id="wrapper" class="open"> REMOVE THIS  -->
{#    <div id="wrapper">#}
{#      <ul id="list">#}
{#        <li>Item</li>#}
{#        <li>Item</li>#}
{#        <li>Item</li>#}
{#        <li>Item</li>#}
{#      </ul>#}
{#    </div>#}


</div>


{#<h6>who i follow </h6>#}
{#        {% for user in object.profile.get_following.all %}  <!-- Myuser QS -->#}
{#          <a href="{% url 'accounts:profile' slug=user.slug %}"> {{ user.username  }}</a> <br>#}
{#        {% endfor %}#}
{#        <hr>#}
{#        <h6>i followed b whom </h6>#}
{#        {% for profile in object.followed_by.all %}  <!-- Profile QS -->#}
{#            <a href="{% url 'accounts:profile' slug=profile.user.slug %}"> {{ profile.user.username }}</a><br>#}
{#        {% endfor %}<hr>#}